- src/v1/controller/login/Login.ts
- src/v1/controller/login/weChat/index.ts
- src/v1/model/types.ts
- src/v1/model/user/WeChat.ts
- src/v1/types/Server.ts
1. modify jwt payload field
2. remove avatar url update when user login
> refactor(login): reduce login response content

- src/v1/controller/login/Login.ts
- src/v1/controller/login/weChat/index.ts
1. sex type modify number type
2. add userID field
> refactor(login): increase login response content

- src/v1/controller/login/weChat/index.ts
- src/v1/controller/room/create/index.ts
- src/v1/controller/room/schedule/index.ts
1. because save cannot use bulk create
> refactor(db): use insert replace save

- src/v1/controller/room/schedule/index.ts
> fix(api): periodic is a must when schedule a room in room/schedule api

- src/v1/controller/room/info/Room.ts
> refactor(api): if endTime is default datetinm then return empty string

- src/v1/controller/room/Router.ts
- src/v1/controller/room/record/Acquire.ts
- src/v1/controller/room/record/Query.ts
- src/v1/controller/room/record/Started.ts
- src/v1/controller/room/record/Stopped.ts
- src/v1/controller/room/record/UpdateLayout.ts
- src/v1/controller/room/utils/Agora.ts
- src/v1/utils/request/agora/Agora.ts
- src/v1/utils/request/agora/AgoraURL.ts
- src/v1/utils/request/agora/Types.ts
1. it is basically used to forward Agora requests
> feat(api): add record api(acquire / query / started / stopped / updateLayout)

- src/v1/controller/room/update/PeriodicSubRoom.ts
1. the begin time must be greater than the end time of the previous room
2. The end time must be less than the begin time of the next room
> refactor(api): adjust the time check logic for updating sub-rooms

- src/v1/controller/room/update/PeriodicSubRoom.ts
Reverts netless-io/flat-server#189
Forgot to modify the comment
> Revert "refactor(api): adjust the time check logic for updating sub-rooms"

- src/v1/controller/room/update/PeriodicSubRoom.ts
1. the begin time cannot be earlier than the begin time of the previous room
2. the end time cannot exceed the end time of the next room
> refactor(api): adjust the code logic to get the previous and next periodic sub room in update/periodic-sub-room api

- src/v1/controller/room/info/PeriodicSubRoom.ts
1. add previousPeriodicRoomBeginTime
2. add nextPeriodicRoomEndTime
3. add needOtherRoomTimeInfo params
> refactor(api): add the information of the previous room and the next room in info/periodic-sub-room

- .github/workflows/main.yml
Reverts netless-io/flat-server#196
fuck github action
> Revert "chore(env): optimize docker env use"

- src/v1/controller/room/join/Ordinary.ts
New RTC is wrongly generated for studuent when joining the same room subsequently.
> fix(api): incorrect rtc when joining ordinary room

- src/v1/controller/room/update/PeriodicSubRoom.ts
judge current beginTime and previous beginTime logic error
> fix(api): update periodic sub room failed

- src/v1/thirdPartyService/RedisService.ts
close: https://github.com/netless-io/flat-server/issues/275
> fix(redis): invalid in optimize redis scan performance

- src/ErrorCode.ts
- src/v1/controller/cloudStorage/Router.ts
- src/v1/controller/cloudStorage/convert/Finish.ts
- src/v1/controller/cloudStorage/convert/Start.ts
- src/v1/controller/cloudStorage/convert/Utils.ts
1. add start convert api
2. add finish convert api
> feat(api): add convert api

- src/v1/controller/cloudStorage/upload/alibabaCloud/Start.ts
- src/v1/controller/cloudStorage/upload/alibabaCloud/Utils.ts
set Content-Disposition header in alibaba cloud oss when upload file
> refactor(alibaba-cloud-oss): set download filename

- src/v1/controller/cloudStorage/Router.ts
- src/v1/controller/cloudStorage/alibabaCloud/remove/index.ts
- src/v1/controller/cloudStorage/upload/alibabaCloud/Utils.ts
> feat(cloud-storage): add remove api

- src/v1/controller/cloudStorage/Router.ts
- src/v1/controller/cloudStorage/alibabaCloud/Utils.ts
- src/v1/controller/cloudStorage/alibabaCloud/remove/index.ts
- src/v1/controller/cloudStorage/alibabaCloud/rename/index.ts
- src/v1/controller/cloudStorage/alibabaCloud/upload/Finish.ts
- src/v1/controller/cloudStorage/alibabaCloud/upload/Start.ts
- src/v1/controller/cloudStorage/alibabaCloud/upload/Utils.ts
- refactor rename path in router
> refactor(cloud-storage): adjust file path

- src/v1/controller/cloudStorage/Router.ts
- src/v1/controller/cloudStorage/upload/cancel.ts
https://github.com/netless-io/flat/pull/480
> feat(cloud-storage): add upload cancel api

- src/v1/controller/login/Constants.ts
- src/v1/controller/login/Login.ts
- src/v1/controller/login/weChat/Utils.ts
- src/v1/controller/login/weChat/mobile/Callback.ts
- src/v1/controller/login/weChat/web/Process.ts
- src/v1/model/user/User.ts
1. rename sex to gender
2. add `None` value in gender
3. remove phone in users
4. remove last_login_platform
> refactor(model): refactor users table

- .eslintrc.js
- package.json
- yarn.lock
1. add and apply @netless/eslint-plugin
> chore(style): strengthen code style

- src/v1/controller/login/github/Callback.ts
origin PR: https://github.com/netless-io/flat-server/pull/338
> refactor(login): improve github callback page

- src/v1/controller/login/github/Callback.ts
we lack the logic to determine whether access_token has been modified,
when access_token is modified / logged out, we should update the latest access_token instead of continuing to use the previous access_token
> fix(login): users need to log in again every time they open in github

- Dockerfile
Fixes #352
Hi @BlackHole1, how does this look?
Let me know if this needs any changes.
Thanks
> Upgrade node version in dockerfile

- src/abstract/controller/index.ts
when auth is false, there is no user object in req
> fix(api): login api failed

- src/model/user/Github.ts
- src/v1/controller/login/Login.ts
- src/v1/controller/login/github/Callback.ts
- src/v1/service/user/User.ts
- src/v1/service/user/UserGithub.ts
- src/v1/service/user/UserWeChat.ts
- src/v1/service/user/__tests__/user.test.ts
- src/v1/service/user/__tests__/userGithub.test.ts
- src/v1/service/user/__tests__/userWeChat.test.ts
* speed ​​up the Login API
* remove access_token column in user_github table
> pref(login): speed up login api

- package.json
- src/thirdPartyService/RedisService.ts
- src/utils/Redis.ts
- src/utils/__tests__/redis.test.ts
- src/v1/controller/room/create/Ordinary.ts
- src/v1/controller/room/create/Periodic.ts
- src/v1/controller/room/create/Utils.ts
- src/v1/controller/room/create/__tests__/utils.test.ts
- src/v1/controller/room/info/Ordinary.ts
- src/v1/controller/room/info/Periodic.ts
- src/v1/controller/room/info/PeriodicSubRoom.ts
- src/v1/controller/room/info/Utils.ts
- src/v1/controller/room/join/index.ts
- src/v1/controller/room/updateStatus/Stopped.ts
- src/v1/controller/room/utils/GenerateInviteCode.ts
- src/v1/controller/room/utils/__tests__/generateInviteCode.test.ts
- yarn.lock
> feat(room): add invite code support

- src/v1/controller/cloudStorage/convert/Start.ts
Reverts netless-io/flat-server#473
> Revert "refactor(cloudStorage): improve pdf file scale to 3"

- src/v1/queue/RTCScreenshot.ts
- src/v1/queue/RTCVoice.ts
- src/v1/queue/index.ts
Start -> Waiting 1m -> Stop -> 10m(success) / 30m(failed) -> Start -> ...
> refactor(queue): improve queue interval time

- src/v1/controller/cloudStorage/convert/Finish.ts
- src/v1/controller/cloudStorage/convert/Start.ts
- src/v1/utils/request/whiteboard/WhiteboardRequest.ts
- src/v1/utils/request/whiteboard/whiteboardRequest.test.ts
Reverts netless-io/flat-server#544
> Revert "refactor(whiteboard): modify file conver api"

- src/index.ts
- src/v2/__tests__/helpers/api/index.ts
Ref: https://github.com/fastify/fastify/issues/4050
> refactor(fastify): improve typeorm-query-runner match params

- src/v2/services/cloud-storage/info.schema.ts
- src/v2/services/cloud-storage/info.ts
- src/v2/services/cloud-storage/info.type.ts
- src/v2/services/cloud-storage/internal/utils/__tests__/file-payload-parse.test.ts
- src/v2/services/cloud-storage/internal/utils/file-payload-parse.ts
Ref: https://github.com/netless-io/flat-server-docs/pull/3
> refactor(cs): improve v2 cs list resp

- src/ErrorCode.ts
- src/model/cloudStorage/Constants.ts
- src/model/cloudStorage/Types.ts
- src/v1/controller/cloudStorage/convert/Finish.ts
- src/v2/__tests__/helpers/db/cloud-storage-files.ts
- src/v2/__tests__/helpers/db/create-cs-files.ts
- src/v2/controllers/cloud-storage/convert/__tests__/finish.test.ts
- src/v2/controllers/cloud-storage/convert/__tests__/start.test.ts
- src/v2/controllers/cloud-storage/convert/finish.ts
- src/v2/controllers/cloud-storage/convert/start.ts
- src/v2/controllers/cloud-storage/routes.ts
- src/v2/services/cloud-storage/__tests__/convert.test.ts
- src/v2/services/cloud-storage/__tests__/info.test.ts
- src/v2/services/cloud-storage/convert.schema.ts
- src/v2/services/cloud-storage/convert.ts
- src/v2/services/cloud-storage/convert.type.ts
- src/v2/services/cloud-storage/info.ts
- src/v2/services/cloud-storage/internal/utils/file-payload-parse.ts
- src/v2/services/whiteboard/__tests__/conversion.test.ts
- src/v2/services/whiteboard/__tests__/projector.test.ts
- src/v2/services/whiteboard/conversion.ts
- src/v2/services/whiteboard/projector.ts
- src/v2/services/whiteboard/token.ts
Ref:
* https://github.com/netless-io/flat-server-docs/pull/5
* https://github.com/netless-io/flat-server-docs/pull/6
> feat(cs): implement file convert api in v2

- src/v2/controllers/cloud-storage/list/__tests__/list.test.ts
- src/v2/services/cloud-storage/__tests__/info.test.ts
- src/v2/services/cloud-storage/info.schema.ts
- src/v2/services/cloud-storage/info.ts
- src/v2/services/cloud-storage/info.type.ts
Doc ref: https://github.com/netless-io/flat-server-docs/pull/11
> refactor(cs): items => files in v2 list resp

- src/v2/__tests__/helpers/db/user.ts
- src/v2/controllers/user/rename/__tests__/rename.test.ts
- src/v2/controllers/user/rename/index.ts
- src/v2/controllers/user/routes.ts
Doc ref: https://github.com/netless-io/flat-server-docs/pull/12
> feat(api): add user rename in v2

- src/v2/controllers/user/routes.ts
- src/v2/controllers/user/upload-avatar/__tests__/finish.test.ts
- src/v2/controllers/user/upload-avatar/__tests__/start.test.ts
- src/v2/controllers/user/upload-avatar/finish.ts
- src/v2/controllers/user/upload-avatar/start.ts
Doc ref: https://github.com/netless-io/flat-server-docs/pull/13
> feat(api): add user upload avatar in v2

- src/v2/services/cloud-storage/__tests__/info.test.ts
- src/v2/services/cloud-storage/__tests__/upload.test.ts
- src/v2/services/cloud-storage/upload.ts
> fix(ap): miss meta.*.currentStep in v1/cs/list

- src/v2/controllers/developer/oauth/__tests__/update.test.ts
- src/v2/controllers/developer/oauth/update.ts
- src/v2/controllers/developer/routes.ts
API doc see: https://github.com/netless-io/flat-server-docs/pull/16
> feat(oauth): add oauth application update info api

- README.md
> doc(readme): Incorrect file path

- src/abstract/controller/index.ts
- src/types/Server.ts
Reverts netless-io/flat-server#704
See: https://gitlab.com/flat-bot/flat-server/-/jobs/3342983811
> Revert "fix(cs): add error message property to flat internal error class"

- src/v1/controller/room/record/Info.ts
> refactor(record): allow accessing recording info from any user

- src/v2/services/user/email.ts
- src/v2/services/user/phone.ts
> fix: v2 login should return the same structure as v1

- config/defaults.yaml
- config/test.yaml
- src/constants/Config.ts
- src/utils/Avatar.ts
- src/utils/ParseConfig.ts
- src/v1/controller/login/agora/Callback.ts
- src/v1/controller/login/apple/jwt.ts
- src/v1/controller/login/phone/Phone.ts
- src/v2/services/user/email.ts
- src/v2/services/user/phone.ts
Note: added a new top-level config `default_avatar`
> refactor: generate different avatars for users

- src/constants/Config.ts
- src/index.ts
- src/utils/ParseConfig.ts
Enable iOS user to open app when click on flat classroom link.
> refactor: get apple-site-association appId from env config

- config/defaults.yaml
- config/test.yaml
- src/thirdPartyService/RedisService.ts
- src/v1/service/user/UserPmi.ts
- src/v2/services/user/pmi.ts
- refactor: generate pmi considering existing invite code
- fix: missing default yaml in 53d3f35e
> refactor: generate pmi considering existing invite code

- src/v1/controller/room/create/Ordinary.ts
- src/v1/controller/room/update/PeriodicSubRoom.ts
- src/v1/controller/room/update/Utils.ts
- src/v1/controller/room/utils/CheckTime.ts
- src/v1/controller/room/utils/__tests__/checkTime.test.ts
- correct wording `beginTimeGreaterThanEndTime`
- fix updating periodic sub room's rules:
- now &leq; begin
- duration(begin, end) &geq; 15 minutes
- prev.begin < begin < next.begin
- end &leq; next.end
> fix: update periodic sub room

- src/ErrorCode.ts
- src/model/index.ts
- src/model/partner/Partner.ts
- src/model/partner/PartnerRoom.ts
- src/thirdPartyService/TypeORMService.ts
- src/v2/__tests__/helpers/api/index.ts
- src/v2/__tests__/helpers/db/index.ts
- src/v2/__tests__/helpers/db/partner.ts
- src/v2/controllers/developer/partner/__tests__/register.test.ts
- src/v2/controllers/developer/partner/create-room.ts
- src/v2/controllers/developer/partner/list-rooms.ts
- src/v2/controllers/developer/partner/register.ts
- src/v2/controllers/developer/partner/remove-room.ts
- src/v2/controllers/developer/routes.ts
- src/v2/dao/index.ts
- src/v2/services/developer/partner.ts
- src/v2/services/room/admin.ts
```js
// Get account (phone or email) user uuid or null if not exist
POST /v2/developer/partner/register { account } => { userUUID }
// Create (schedule) a room for user and teacher (owner)
POST /v2/developer/partner/create-room {
userUUID,
ownerUUID,
title,
type: "OneToOne",
beginTime: Date.now(),
endTime: Date.now() + 3600000,
} =>
{ roomUUID, inviteCode }
// List rooms for some user or all
POST /v2/developer/partner/list-rooms { userUUID? } => [{
roomUUID,
title,
roomType,
roomStatus: "Idle",
beginTime,
endTime,
}]
// Remove a room
POST /v2/developer/partner/remove-room { roomUUID } => {}
```
All the partner APIs must have a header field `x-flat-partner` filled with the partner ID. The partner IDs are manually created in database for now.
The partner can only query and manipulate rooms …
> feat: add developer partner APIs

- src/model/room/Room.ts
- src/v1/controller/room/create/__tests__/ordinary.test.ts
- src/v1/controller/room/info/Ordinary.ts
- src/v1/controller/room/info/PeriodicSubRoom.ts
- src/v1/controller/room/list/index.ts
- src/v1/controller/room/record/Started.ts
- src/v1/controller/room/record/agora/Started.ts
DDL:
```sql
ALTER TABLE `rooms` ADD COLUMN `has_record` tinyint NOT NULL DEFAULT '0';
```
DML:
```sql
-- confirm affected rows
select rr.`room_uuid`, count(*) from `room_records` rr INNER JOIN `rooms` r on r.`room_uuid` = rr.`room_uuid` where rr.`is_delete` = 0 and r.`is_delete` = 0 and r.has_record = 1 group by rr.`room_uuid` 
update rooms set has_record=1 where `room_uuid` in (
select rr.`room_uuid` as room_uuid from `room_records` rr  where rr.`is_delete` = 0 group by rr.`room_uuid` 
)
```
> `rooms` add column `has_record` for optimize room history list

- .gitlab-ci.yml
see https://forum.gitlab.com/t/docker-build-fails-with-cgroups-mountpoint-error/104172/7
>  chore(sa): fix gitlab ci build

- .gitlab-ci.yml
- src/ErrorCode.ts
- src/model/index.ts
- src/model/partner/Partner.ts
- src/model/partner/PartnerRoom.ts
- src/model/room/Room.ts
- src/thirdPartyService/TypeORMService.ts
- src/v1/controller/room/create/__tests__/ordinary.test.ts
- src/v1/controller/room/info/Ordinary.ts
- src/v1/controller/room/info/PeriodicSubRoom.ts
- src/v1/controller/room/list/__tests__/list.test.ts
- src/v1/controller/room/list/index.ts
- src/v1/controller/room/record/Started.ts
- src/v1/controller/room/record/agora/Started.ts
- src/v2/__tests__/helpers/api/index.ts
- src/v2/__tests__/helpers/db/index.ts
- src/v2/__tests__/helpers/db/partner.ts
- src/v2/controllers/developer/partner/__tests__/register.test.ts
- src/v2/controllers/developer/partner/create-room.ts
- src/v2/controllers/developer/partner/list-rooms.ts
- src/v2/controllers/developer/partner/register.ts
- src/v2/controllers/developer/partner/remove-room.ts
- src/v2/controllers/developer/routes.ts
- src/v2/dao/index.ts
- src/v2/services/developer/partner.ts
- src/v2/services/room/admin.ts
DDL:
https://github.com/netless-io/flat-server/pull/831
https://github.com/netless-io/flat-server/pull/834
> feat(rooms): partner APIs and optimize room history list

- package.json
- yarn.lock
This reverts commit bfaf51fdedbd5115283d4de2ece0a3b86db6aef3.
> Revert "chore(deps): bump fastify from 4.8.1 to 4.10.2 (#707)"

- Dockerfile
Reverts netless-io/flat-server#872
> Revert "upgrade runtime node to lts"
